podTemplate(yaml: '''
  apiVersion: v1 
  kind: Pod
  spec:
    containers:
    - name: gradle
      image: gradle:6.3-jdk14
      command:
      - sleep
      args:
      - 99d
      volumeMounts:
      - name: shared-storage
        mountPath: /mnt
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
      - sleep
      args:
      - 9999999
      volumeMounts:
      - name: shared-storage
        mountPath: /mnt
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    restartPolicy: Never
    volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: kaniko-pv-claim
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
        - key: .dockerconfigjson
          path: config.json'''
) 
{
  node(POD_LABEL) {
    stage('Build a gradle project') {
      git 'https://github.com/harvash/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('gradle') {
        stage('Build a gradle project') {
          sh '''pwd
                cd Chapter08/sample1
                chmod +x gradlew
                ./gradlew build
                ls -l ./build/libs
                cp ./build/libs/calculator-0.0.1-SNAPSHOT.jar /mnt
                chmod +x /mnt/calculator-0.0.1-SNAPSHOT.jar
                ls -l /mnt'''
        }
      }
    }
    stage('Build Java Image') {
      container('kaniko') {
        stage('Build a gradle project') {
          sh '''echo 'FROM openjdk:8-jre' > Dockerfile
                echo 'COPY ./calculator-0.0.1-SNAPSHOT.jar app.jar' >> Dockerfile
                echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
                cat Dockerfile
                ls -l /mnt
                cp /mnt/calculator-0.0.1-SNAPSHOT.jar app.jar
                chmod +x app.jar
                pwd
                ls -al
                /kaniko/executor --context `pwd` --destination harvash/hello-kaniko:1.0'''
        }
      } 
    }
  }     
}